<?php
    namespace Model;
    use Model\Util;
    class SAP extends Util {
        protected function setSlsGroup($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = $item->vkgrp;
                $sqls = "INSERT INTO zsgr     ( objky,
                                                vkgrp,
                                                objnm )
                                      values  ( :objky,
                                                :vkgrp,
                                                :objnm ) 
                            ON DUPLICATE KEY UPDATE 
                                vkgrp  = values(vkgrp),
                                objnm  = values(objnm),
                                cngdt  = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->vkgrp,
                                        $item->bezei));
            }
            $conn = null;
        }
        protected function setCustomer($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = str_pad($item->kunnr, 10, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO customer ( objky,
                                                objnm, 
                                                kunnr,
                                                name1,
                                                name2,
                                                name4,
                                                land1,
                                                ort01,
                                                ort02,
                                                pstlz,
                                                ktokd,
                                                lifnr,
                                                spras,
                                                regio ) 
                                      values  (:objky,
                                               :objnm,
                                               :kunnr,
                                               :name1,
                                               :name2,
                                               :name4,
                                               :land1,
                                               :ort01,
                                               :ort02,
                                               :pstlz,
                                               :ktokd,
                                               :lifnr,
                                               :spras,
                                               :regio ) 
                            ON DUPLICATE KEY UPDATE 
                                    objnm = values(objnm),
                                    lifnr = values(kunnr),
                                    name1 = values(name1),
                                    name2 = values(name2),
                                    name4 = values(name4),
                                    land1 = values(land1),
                                    ort01 = values(ort01),
                                    ort02 = values(ort02),
                                    pstlz = values(pstlz),
                                    ktokd = values(ktokd),
                                    lifnr = values(lifnr),
                                    spras = values(spras),
                                    regio = values(regio),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->name1,
                                        $item->kunnr,
                                        $item->name1,
                                        $item->name2,
                                        $item->name4,
                                        $item->land1,
                                        $item->ort01,
                                        $item->ort02,
                                        $item->pstlz,
                                        $item->ktokd,
                                        $item->lifnr,
                                        $item->spras,
                                        $item->regio));
            }
            $conn = null;
        }
        protected function setSOItem($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->vbeln}".str_pad($item->posnr, 6, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zord     ( objky, 
                                                vbeln, 
                                                posnr, 
                                                bukrs, 
                                                vkorg, 
                                                vtweg, 
                                                spart, 
                                                kunnr, 
                                                aedat, 
                                                matnr, 
                                                arktx, 
                                                werks, 
                                                lgort, 
                                                charg, 
                                                matkl, 
                                                menge, 
                                                vrkme, 
                                                netwr,
                                                waers) 
                                      values  ( :objky,
                                                :vbeln,
                                                :posnr,
                                                :bukrs,
                                                :vkorg,
                                                :vtweg,
                                                :spart,
                                                :kunnr,
                                                :aedat,
                                                :matnr,
                                                :arktx,
                                                :werks,
                                                :lgort,
                                                :charg,
                                                :matkl,
                                                :menge,
                                                :vrkme,
                                                :netwr,
                                                :waers)
                            ON DUPLICATE KEY UPDATE 
                                    vbeln = values(vbeln),
                                    posnr = values(posnr),
                                    bukrs = values(bukrs),
                                    vkorg = values(vkorg),
                                    vtweg = values(vtweg),
                                    spart = values(spart),
                                    kunnr = values(kunnr),
                                    aedat = values(aedat),
                                    matnr = values(matnr),
                                    arktx = values(arktx),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    charg = values(charg),
                                    matkl = values(matkl),
                                    menge = values(menge),
                                    vrkme = values(vrkme),
                                    netwr = values(netwr),
                                    waers = values(waers),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->vbeln,
                                        $item->posnr,
                                        $item->bukrs_vf,
                                        $item->vkorg,
                                        $item->vtweg,
                                        $item->spart,
                                        $item->kunnr,
                                        $item->aedat,
                                        $item->matnr,
                                        $item->arktx,
                                        $item->werks,
                                        $item->lgort,
                                        $item->charg,
                                        $item->matkl,
                                        $item->kwmeng,
                                        $item->vrkme,
                                        $item->netwr,
                                        $item->waerk));
            }
            $conn = null;
        }
        protected function setSOSline($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->vbeln}".str_pad($item->posnr, 5, "0", STR_PAD_LEFT).str_pad($item->etenr, 4, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zsis    (  objky, 
                                                vbeln,
                                                posnr,
                                                etenr,
                                                kunnr,
                                                matnr,
                                                arktx,
                                                ettyp,
                                                lfrel,
                                                edatu,
                                                ezeit,
                                                wmeng,
                                                bmeng,
                                                vrkme,
                                                lmeng,
                                                meins,
                                                bddat,
                                                bdart,
                                                plart,
                                                etene,
                                                cngdt)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                      values   (:objky,
                                                :vbeln,
                                                :posnr,
                                                :etenr,
                                                :kunnr,
                                                :matnr,
                                                :arktx,
                                                :ettyp,
                                                :lfrel,
                                                :edatu,
                                                :ezeit,
                                                :wmeng,
                                                :bmeng,
                                                :vrkme,
                                                :lmeng,
                                                :meins,
                                                :bddat,
                                                :bdart,
                                                :plart,
                                                :etene,
                                                 NOW()) 
                            ON DUPLICATE KEY UPDATE 
                                    objky = values(objky),
                                    vbeln = values(vbeln),
                                    posnr = values(posnr),
                                    etenr = values(etenr),
                                    kunnr = values(kunnr),
                                    matnr = values(matnr),
                                    arktx = values(arktx),
                                    ettyp = values(ettyp),
                                    lfrel = values(lfrel),
                                    edatu = values(edatu),
                                    ezeit = values(ezeit),
                                    wmeng = values(wmeng),
                                    bmeng = values(bmeng),
                                    vrkme = values(vrkme),
                                    lmeng = values(lmeng),
                                    meins = values(meins),
                                    bddat = values(bddat),
                                    bdart = values(bdart),
                                    plart = values(plart),
                                    etene = values(etene),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky, 
                                        $item->vbeln,
                                        $item->posnr,
                                        $item->etenr,
                                        $item->kunnr,
                                        $item->matnr,
                                        $item->arktx,
                                        $item->ettyp,
                                        $item->lfrel,
                                        $item->edatu,
                                        $item->ezeit,
                                        $item->wmeng,
                                        $item->bmeng,
                                        $item->vrkme,
                                        $item->lmeng,
                                        $item->meins,
                                        $item->bddat,
                                        $item->bdart,
                                        $item->plart,
                                        $item->etene ));
            }
            $conn = null;
        }
        protected function setShipment($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->tknum}";
                $sqls = "INSERT INTO zshp   (   objky,
                                                tknum,
                                                vbtyp,
                                                shtyp,
                                                tplst,
                                                ernam,
                                                erdat,
                                                erzet,
                                                vsart,
                                                vsbed,
                                                route,
                                                signi,
                                                exti1,
                                                exti2,
                                                tpbez,
                                                text1,
                                                text2,
                                                text3,
                                                text4,
                                                sttrg,
                                                tdlnr,
                                                lifnr,
                                                zzins )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :tknum,
                                                :vbtyp,
                                                :shtyp,
                                                :tplst,
                                                :ernam,
                                                :erdat,
                                                :erzet,
                                                :vsart,
                                                :vsbed,
                                                :route,
                                                :signi,
                                                :exti1,
                                                :exti2,
                                                :tpbez,
                                                :text1,
                                                :text2,
                                                :text3,
                                                :text4,
                                                :sttrg,
                                                :tdlnr,
                                                :lifnr,
                                                :zzins ) 
                            ON DUPLICATE KEY UPDATE 
                                    tknum = values(tknum),
                                    vbtyp = values(vbtyp),
                                    shtyp = values(shtyp),
                                    tplst = values(tplst),
                                    ernam = values(ernam),
                                    erdat = values(erdat),
                                    erzet = values(erzet),
                                    vsart = values(vsart),
                                    vsbed = values(vsbed),
                                    route = values(route),
                                    signi = values(signi),
                                    exti1 = values(exti1),
                                    exti2 = values(exti2),
                                    tpbez = values(tpbez),
                                    text1 = values(text1),
                                    text2 = values(text2),
                                    text3 = values(text3),
                                    text4 = values(text4),
                                    sttrg = values(sttrg),
                                    tdlnr = values(tdlnr),
                                    lifnr = values(lifnr),
                                    zzins = values(zzins),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->tknum,
                                        $item->vbtyp,
                                        $item->shtyp,
                                        $item->tplst,
                                        $item->ernam,
                                        $item->erdat,
                                        $item->erzet,
                                        $item->vsart,
                                        $item->vsbed,
                                        $item->route,
                                        $item->signi,
                                        $item->exti1,
                                        $item->exti2,
                                        $item->tpbez,
                                        $item->text1,
                                        $item->text2,
                                        $item->text3,
                                        $item->text4,
                                        $item->sttrg,
                                        $item->tdlnr,
                                        $item->lifnr,
                                        $item->zzins));
            }
            $conn = null;
        }
        protected function setDelivery($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->vbeln}".str_pad($item->posnr, 6, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zobd   (   objky,
                                                vbeln,
                                                posnr,
                                                ernam,
                                                erdat,
                                                erzet,
                                                vstel,
                                                lfart,
                                                ablad,
                                                route,
                                                lifsk,
                                                vbtyp,
                                                lifnr,
                                                kunnr,
                                                kunag,
                                                brgew,
                                                ntgew,
                                                gewei,
                                                anzpk,
                                                pstyv,
                                                matnr,
                                                arktx,
                                                werks,
                                                lgort,
                                                charg,
                                                lfimg,
                                                meins,
                                                vrkme,
                                                vbelv,
                                                posnv,
                                                vgbel,
                                                vgpos)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :vbeln,
                                                :posnr,
                                                :ernam,
                                                :erdat,
                                                :erzet,
                                                :vstel,
                                                :lfart,
                                                :ablad,
                                                :route,
                                                :lifsk,
                                                :vbtyp,
                                                :lifnr,
                                                :kunnr,
                                                :kunag,
                                                :brgew,
                                                :ntgew,
                                                :gewei,
                                                :anzpk,
                                                :pstyv,
                                                :matnr,
                                                :arktx,
                                                :werks,
                                                :lgort,
                                                :charg,
                                                :lfimg,
                                                :meins,
                                                :vrkme,
                                                :vbelv,
                                                :posnv,
                                                :vgbel,
                                                :vgpos) 
                            ON DUPLICATE KEY UPDATE 
                                    objky = values(objky),
                                    vbeln = values(vbeln),
                                    posnr = values(posnr),
                                    ernam = values(ernam),
                                    erdat = values(erdat),
                                    erzet = values(erzet),
                                    vstel = values(vstel),
                                    lfart = values(lfart),
                                    ablad = values(ablad),
                                    route = values(route),
                                    lifsk = values(lifsk),
                                    vbtyp = values(vbtyp),
                                    lifnr = values(lifnr),
                                    kunnr = values(kunnr),
                                    kunag = values(kunag),
                                    brgew = values(brgew),
                                    ntgew = values(ntgew),
                                    gewei = values(gewei),
                                    anzpk = values(anzpk),
                                    pstyv = values(pstyv),
                                    matnr = values(matnr),
                                    arktx = values(arktx),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    charg = values(charg),
                                    lfimg = values(lfimg),
                                    meins = values(meins),
                                    vrkme = values(vrkme),
                                    vbelv = values(vbelv),
                                    posnv = values(posnv),
                                    vgbel = values(vgbel),
                                    vgpos = values(vgpos),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->vbeln,
                                        $item->posnr,
                                        $item->ernam,
                                        $item->erdat,
                                        $item->erzet,
                                        $item->vstel,
                                        $item->lfart,
                                        $item->ablad,
                                        $item->route,
                                        $item->lifsk,
                                        $item->vbtyp,
                                        $item->lifnr,
                                        $item->kunnr,
                                        $item->kunag,
                                        $item->brgew,
                                        $item->ntgew,
                                        $item->gewei,
                                        $item->anzpk,
                                        $item->pstyv,
                                        $item->matnr,
                                        $item->arktx,
                                        $item->werks,
                                        $item->lgort,
                                        $item->charg,
                                        $item->lfimg,
                                        $item->meins,
                                        $item->vrkme,
                                        $item->vbelv,
                                        $item->posnv,
                                        $item->vgbel,
                                        $item->vgpos ));
            }
            $conn = null;
        }
        protected function setGoodsMvt($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->mblnr}".str_pad($item->mjahr, 4, "0", STR_PAD_LEFT).str_pad($item->zeile, 4, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zmvt    (  objky,
                                                mblnr, 
                                                mjahr,
                                                zeile,
                                                bwart,
                                                matnr,
                                                txz01,
                                                werks,
                                                lgort,
                                                charg,
                                                insmk,
                                                sobkz,
                                                kunnr,
                                                waers,
                                                bnbtr,
                                                menge,
                                                meins,
                                                lsmng,
                                                lsmeh,
                                                lfbja,
                                                lfbnr,
                                                sjahr,
                                                smbln,
                                                bukrs,
                                                belnr,
                                                buzei,
                                                buzum,
                                                rspos,
                                                vgart,
                                                blart,
                                                budat,
                                                cpudt,
                                                cputm,
                                                xblnr,
                                                bktxt,
                                                xabln,
                                                shkzg)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :mblnr, 
                                                :mjahr,
                                                :zeile,
                                                :bwart,
                                                :matnr,
                                                :txz01,
                                                :werks,
                                                :lgort,
                                                :charg,
                                                :insmk,
                                                :sobkz,
                                                :kunnr,
                                                :waers,
                                                :bnbtr,
                                                :menge,
                                                :meins,
                                                :lsmng,
                                                :lsmeh,
                                                :lfbja,
                                                :lfbnr,
                                                :sjahr,
                                                :smbln,
                                                :bukrs,
                                                :belnr,
                                                :buzei,
                                                :buzum,
                                                :rspos,
                                                :vgart,
                                                :blart,
                                                :budat,
                                                :cpudt,
                                                :cputm,
                                                :xblnr,
                                                :bktxt,
                                                :xabln,
                                                :shkzg) 
                            ON DUPLICATE KEY UPDATE 
                                    mblnr = values(mblnr), 
                                    mjahr = values(mjahr),
                                    zeile = values(zeile),
                                    bwart = values(bwart),
                                    matnr = values(matnr),
                                    txz01 = values(txz01),
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    charg = values(charg),
                                    insmk = values(insmk),
                                    sobkz = values(sobkz),
                                    kunnr = values(kunnr),
                                    waers = values(waers),
                                    bnbtr = values(bnbtr),
                                    menge = values(menge),
                                    meins = values(meins),
                                    lsmng = values(lsmng),
                                    lsmeh = values(lsmeh),
                                    lfbja = values(lfbja),
                                    lfbnr = values(lfbnr),
                                    sjahr = values(sjahr),
                                    smbln = values(smbln),
                                    bukrs = values(bukrs),
                                    belnr = values(belnr),
                                    buzei = values(buzei),
                                    buzum = values(buzum),
                                    rspos = values(rspos),
                                    vgart = values(vgart),
                                    blart = values(blart),
                                    budat = values(budat),
                                    cpudt = values(cpudt),
                                    cputm = values(cputm),
                                    xblnr = values(xblnr),
                                    bktxt = values(bktxt),
                                    xabln = values(xabln),
                                    shkzg = values(shkzg),
                                    cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->mblnr, 
                                        $item->mjahr,
                                        $item->zeile,
                                        $item->bwart,
                                        $item->matnr,
                                        $item->maktx,
                                        $item->werks,
                                        $item->lgort,
                                        $item->charg,
                                        $item->insmk,
                                        $item->sobkz,
                                        $item->kunnr,
                                        $item->waers,
                                        $item->bnbtr,
                                        $item->menge,
                                        $item->meins,
                                        $item->lsmng,
                                        $item->lsmeh,
                                        $item->lfbja,
                                        $item->lfbnr,
                                        $item->sjahr,
                                        $item->smbln,
                                        $item->bukrs,
                                        $item->belnr,
                                        $item->buzei,
                                        $item->buzum,
                                        $item->rspos,
                                        $item->vgart,
                                        $item->blart,
                                        $item->budat,
                                        $item->cpudt,
                                        $item->cputm,
                                        $item->xblnr,
                                        $item->bktxt,
                                        $item->xabln,
                                        $item->shkzg));
            }
            $conn = null;
        }
        protected function setInvoice($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->vbeln}".str_pad($item->posnr, 6, "0", STR_PAD_LEFT);
                $sqls = "INSERT INTO zinv   (   objky,
                                                vbeln,
                                                posnr,
                                                kunnr,
                                                xblnr,
                                                fkdat,
                                                matnr,
                                                arktx,
                                                werks,
                                                fkimg,
                                                vrkme,
                                                vgbel,
                                                vgpos,
                                                aubel,
                                                aupos )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :vbeln,
                                                :posnr,
                                                :kunnr,
                                                :xblnr,
                                                :fkdat,
                                                :matnr,
                                                :arktx,
                                                :werks,
                                                :fkimg,
                                                :vrkme,
                                                :vgbel,
                                                :vgpos,
                                                :aubel,
                                                :aupos ) 
                            ON DUPLICATE KEY UPDATE 
                                objky = values(objky),
                                vbeln = values(vbeln),
                                posnr = values(posnr),
                                kunnr = values(kunnr),
                                xblnr = values(xblnr),
                                fkdat = values(fkdat),
                                matnr = values(matnr),
                                arktx = values(arktx),
                                werks = values(werks),
                                fkimg = values(fkimg),
                                vrkme = values(vrkme),
                                vgbel = values(vgbel),
                                vgpos = values(vgpos),
                                aubel = values(aubel),
                                aupos = values(aupos),
                                cngdt = NOW()";

                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,
                                        $item->vbeln,
                                        $item->posnr,
                                        $item->kunag,
                                        $item->xblnr,
                                        $item->fkdat,
                                        $item->matnr,
                                        $item->arktx,
                                        $item->werks,
                                        $item->fkimg,
                                        $item->vrkme,
                                        $item->vgbel,
                                        $item->vgpos,
                                        $item->aubel,
                                        $item->aupos));
            }
            $conn = null;
        }
        
        
        protected function setPlant($rqst) {
            $conn = $this->connect();
            
            foreach($rqst->items as $item) {
                $item->objky = "{$item->werks}";
                $sqls = "INSERT INTO plants (   objky,
                                                objnm, 
                                                werks )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                      values  ( :objky,
                                                :objnm, 
                                                :werks) 
                            ON DUPLICATE KEY UPDATE 
                                objnm = values(objnm), 
                                werks = values(werks),
                                cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->werks,   
                                        $item->name1, 
                                        $item->werks));
            }
            $conn = null;
        }
        protected function setStrLoc($rqst) {
            $conn = $this->connect();
            foreach($rqst->items as $item) {
                $item->objky = "{$item->werks}{$item->lgort}";
                $sqls = "INSERT INTO stor_loc (objky,
                                                objnm, 
                                                werks,
                                                lgort,
                                                cngdt )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                    values  (   :objky,
                                                :objnm, 
                                                :werks,
                                                :lgort,
                                                NOW()) 
                        ON DUPLICATE KEY UPDATE 
                                    objnm = values(objnm), 
                                    werks = values(werks),
                                    lgort = values(lgort),
                                    cngdt = NOW()";
                $stmt = $conn->prepare($sqls);
                $stmt->execute(array(   $item->objky,   
                                        $item->lgobe, 
                                        $item->werks,
                                        $item->lgort));
            }
            $conn = null;
            
        }
    }
    